name: IOS
on: 
  push:
    tags:
      - v*
  workflow_dispatch:
  
  
jobs:
  build:
    name: Build
    runs-on: macos-10.14
    # 10.15 / 10.13.6
    strategy:
      matrix:
        # qt_ver: [5.12.10, 5.15.2]
        qt_ver: [5.12.3]
        qt_target: [ios]
        xcode: [10.1]
    steps:
      - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
      - name: Install Qt
        # if: steps.cacheqt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2.10.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: ${{ matrix.qt_target }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build ios
        run: |
          qmake -r -spec macx-ios-clang CONFIG+=release CONFIG+=iphoneos
          make
      - name: show filetrees
        run: |
          ls -R
          mkdir stellariumMobile
          mkdir stellariumMobile/Payload
          cp -r Release-iphonesimulator/stellariumMobile.app stellariumMobile/Payload/stellariumMobile.app
          cd stellariumMobile
          zip -r stellariumMobile-${{ matrix.qt_ver }}-${{ matrix.xcode }}.ipa Payload
      - uses: actions/upload-artifact@v1
        with:
          name: stellariumMobile-${{ matrix.qt_ver }}-${{ matrix.xcode }}.ipa
          path: stellariumMobile/stellariumMobile-${{ matrix.qt_ver }}-${{ matrix.xcode }}.ipa